const myAppointments = [
  {
    especialidad: "otorrino",
    date: "2025-06-11",
    time: "13:00",
    cobertura: true,
    Estado: "Cancelado",
    idUser: 6,
  },
  {
    especialidad: "cardiología",
    date: "2025-07-15",
    time: "09:30",
    cobertura: false,
    Estado: "Cancelado",
    idUser: 1,
  },
  {
    especialidad: "neurología",
    date: "2025-08-20",
    time: "11:00",
    cobertura: true,
    Estado: "Cancelado",
    idUser: 2,
  },
  {
    especialidad: "traumatología",
    date: "2025-09-10",
    time: "15:30",
    cobertura: false,
    Estado: "Activo",
    idUser: 3,
  },
  {
    especialidad: "dermatología",
    date: "2025-10-05",
    time: "08:00",
    cobertura: true,
    Estado: "Activo",
    idUser: 4,
  },
  {
    especialidad: "gastroenterología",
    date: "2025-11-18",
    time: "14:00",
    cobertura: false,
    Estado: "Activo",
    idUser: 5,
  },
  {
    especialidad: "urología",
    date: "2025-12-01",
    time: "10:30",
    cobertura: true,
    Estado: "Activo",
    idUser: 7,
  },
  {
    especialidad: "pediatría",
    date: "2025-12-25",
    time: "12:00",
    cobertura: false,
    Estado: "Activo",
    idUser: 8,
  },
  {
    especialidad: "oftalmología",
    date: "2025-06-20",
    time: "16:00",
    cobertura: true,
    Estado: "Activo",
    idUser: 9,
  },
  {
    especialidad: "psiquiatría",
    date: "2025-07-05",
    time: "17:30",
    cobertura: false,
    Estado: "Activo",
    idUser: 10,
  },
];
export default myAppointments;
